from django.urls import path, re_path

from ...api_views.base import views

urlpatterns = [
    path(
        "job-positions/",
        views.JobPositionView.as_view(),
        name="api-job_position_detail",
    ),
    path(
        "job-positions/<int:pk>/",
        views.JobPositionView.as_view(),
        name="api-job_position_detail_with_pk",
    ),
    path("job-roles/", views.JobRoleView.as_view(), name="api-job_roles_details"),
    path(
        "job-roles/<int:pk>/",
        views.JobRoleView.as_view(),
        name="api-job_roles_details_with_pk",
    ),
    path("companies/", views.CompanyView.as_view(), name="api-companies_detail"),
    path(
        "companies/<int:pk>/",
        views.CompanyView.as_view(),
        name="api-companies_detail_with_pk",
    ),
    path("departments/", views.DepartmentView.as_view(), name="api-department_detail"),
    path(
        "departments/<int:pk>/",
        views.DepartmentView.as_view(),
        name="api-department_detail_with_pk",
    ),
    path("worktypes/", views.WorkTypeView.as_view(), name="api-worktype_detail"),
    path(
        "worktypes/<int:pk>/",
        views.WorkTypeView.as_view(),
        name="api-worktype_detail_with_pk",
    ),
    path(
        "rotating-worktypes/",
        views.RotatingWorkTypeView.as_view(),
        name="api-rotating_worktypes_detail",
    ),
    path(
        "rotating-worktypes/<int:pk>/",
        views.RotatingWorkTypeView.as_view(),
        name="api-rotating_worktypes_detail_with_pk",
    ),
    path(
        "rotating-worktype-assigns/",
        views.RotatingWorkTypeAssignView.as_view(),
        name="api-rotating_worktype_assign_detail",
    ),
    path(
        "individual-rotating-worktypes/",
        views.IndividualRotatingWorktypesView.as_view(),
        name="api-individual-worktype",
    ),
    path(
        "individual-rotating-worktypes/<int:pk>",
        views.IndividualRotatingWorktypesView.as_view(),
        name="api-individual-worktype",
    ),
    path(
        "individual-worktype-request/",
        views.IndividualWorkTypeRequestView.as_view(),
        name="api-individual-worktype-request",
    ),
    path(
        "individual-worktype-request/<int:pk>",
        views.IndividualWorkTypeRequestView.as_view(),
        name="api-individual-worktype-request",
    ),
    path(
        "rotating-worktype-assigns/<int:pk>/",
        views.RotatingWorkTypeAssignView.as_view(),
        name="api-rotating_worktype_assign_detail_with_pk",
    ),
    path(
        "employee-shift-day/",
        views.EmployeeShiftDayView.as_view(),
        name="api-employee_shift_day",
    ),
    path(
        "employee-shift/",
        views.EmployeeShiftView.as_view(),
        name="api-employee_shift_detail",
    ),
    path(
        "employee-shift/<int:pk>/",
        views.EmployeeShiftView.as_view(),
        name="api-employee_shift_detail_with_pk",
    ),
    path(
        "employee-shift-schedules/",
        views.EmployeeShiftScheduleView.as_view(),
        name="api-employee_shift_schedule_detail",
    ),
    path(
        "employee-shift-schedules/<int:pk>/",
        views.EmployeeShiftScheduleView.as_view(),
        name="api-employee_shift_schedule_detail_with_pk",
    ),
    path(
        "rotating-shifts/",
        views.RotatingShiftView.as_view(),
        name="api-rotating_shifts_detail",
    ),
    path(
        "rotating-shifts/<int:pk>/",
        views.RotatingShiftView.as_view(),
        name="api-rotating_shifts_detail_with_pk",
    ),
    path(
        "rotating-shift-assigns/",
        views.RotatingShiftAssignView.as_view(),
        name="api-rotating_shift_assigns_detail",
    ),
    path(
        "rotating-shift-assigns/<int:pk>/",
        views.RotatingShiftAssignView.as_view(),
        name="api-rotating_shift_assigns_detail_with_pk",
    ),
    path(
        "individual-rotating-shifts/",
        views.IndividualRotatingShiftView.as_view(),
        name="api-individual-worktype-request",
    ),
    path(
        "individual-rotating-shifts/<int:pk>",
        views.IndividualRotatingShiftView.as_view(),
        name="api-individual-worktype-request",
    ),
    path(
        "worktype-requests/",
        views.WorkTypeRequestView.as_view(),
        name="api-worktype_requests_detail",
    ),
    path(
        "worktype-requests/<int:pk>/",
        views.WorkTypeRequestView.as_view(),
        name="api-worktype_requests_detail_with_pk",
    ),
    path(
        "worktype-requests-cancel/<int:pk>/",
        views.WorkTypeRequestCancelView.as_view(),
        name="api-worktype_requests_detail_with_pk",
    ),
    path(
        "worktype-requests-approve/<int:pk>/",
        views.WorkRequestApproveView.as_view(),
        name="api-worktype_requests_detail_with_pk",
    ),
    path(
        "shift-requests/",
        views.ShiftRequestView.as_view(),
        name="api-shift_requests_detail",
    ),
    path(
        "shift-requests/<int:pk>/",
        views.ShiftRequestView.as_view(),
        name="api-shift_requests_detail_with_pk",
    ),
    path(
        "individual-shift-request/",
        views.IndividualShiftRequestView.as_view(),
        name="api-individual-worktype-request",
    ),
    path(
        "individual-shift-request/<int:pk>",
        views.IndividualShiftRequestView.as_view(),
        name="api-individual-worktype-request",
    ),
    path(
        "shift-request-approve/<int:pk>",
        views.ShiftRequestApproveView.as_view(),
        name="api-shift-requests-approve",
    ),
    path(
        "shift-request-bulk-approve",
        views.ShiftRequestBulkApproveView.as_view(),
        name="api-shift-request-bulk-approve",
    ),
    path(
        "shift-request-cancel/<int:pk>",
        views.ShiftRequestCancelView.as_view(),
        name="api-shift-request-cancel",
    ),
    path(
        "shift-request-bulk-cancel",
        views.ShiftRequestBulkCancelView.as_view(),
        name="api-shift-request-bulk-cancel",
    ),
    path(
        "shift-request-delete/<int:pk>",
        views.ShiftRequestDeleteView.as_view(),
        name="api-shift-request-delete",
    ),
    path(
        "shift-request-bulk-delete",
        views.ShiftRequestDeleteView.as_view(),
        name="api-shift-request-bulk-delete",
    ),
    path(
        "shift-request-export",
        views.ShiftRequestExportView.as_view(),
        name="api-shift-request-export",
    ),
    path(
        "shift-request-allocation/<int:id>",
        views.ShiftRequestAllocationView.as_view(),
        name="api-shift-request-allocation",
    ),
    path(
        "work-type-request-export",
        views.WorkTypeRequestExport.as_view(),
        name="api-work-type-request-export",
    ),
    path(
        "rotating-shift-assign-export",
        views.RotatingShiftAssignExport.as_view(),
        name="api-rotating-shift-assigns-export",
    ),
    path(
        "rotating-shift-assign-bulk-archive/<str:status>",
        views.RotatingShiftAssignBulkArchive.as_view(),
        name="api-rotating-shift-assigns-archive",
    ),
    path(
        "rotating-shift-assign-bulk-delete",
        views.RotatingShiftAssignBulkDelete.as_view(),
        name="api-rotating-shift-assigns-bulk-delete",
    ),
    path(
        "rotating-work-type-assign-export",
        views.RotatingWorkTypeAssignExport.as_view(),
        name="api-rotating-work-type-assign-export",
    ),
    path(
        "rotating-work-type-assign-bulk-archive/<str:status>",
        views.RotatingWorkTypeAssignBulkArchive.as_view(),
        name="api-rotating-work-type-assign-bulk-archive",
    ),
    path(
        "rotating-work-type-assign-bulk-delete",
        views.RotatingWorkTypeAssignBulkDelete.as_view(),
        name="api-rotating-work-type-assign-bulk-delete",
    ),
    path(
        "rotating-worktype-create-permission-check/<int:id>",
        views.RotatingWorKTypePermissionCheck.as_view(),
        name="api-rotating-worktype-create-permission-check",
    ),
    path(
        "rotating-shift-create-permission-check/<int:id>",
        views.RotatingShiftPermissionCheck.as_view(),
        name="api-rotating-shift-create-permission-check",
    ),
    path(
        "shift-request-approve-permission-check",
        views.ShiftRequestApprovePermissionCheck.as_view(),
        name="api-rotating-worktype-create-permission-check",
    ),
    path(
        "worktype-request-approve-permission-check",
        views.WorktypeRequestApprovePermissionCheck.as_view(),
        name="api-rotating-shift-create-permission-check",
    ),
    path(
        "employee-tab-permission-check",
        views.EmployeeTabPermissionCheck.as_view(),
        name="api-rotating-shift-create-permission-check",
    ),
    path(
        "check-user-level", views.CheckUserLevel.as_view(), name="api-check-user-level"
    ),
    path(
        "biometric-attendance/",
        views.BiometricAttendanceAPIView.as_view(),
        name="api-biometric-attendance",
    ),
    path(
        "attendance-allowed-ip/",
        views.AttendanceAllowedIPAPIView.as_view(),
        name="api-attendance-allowed-ip",
    ),
    path(
        "general-settings/",
        views.GeneralSettingsAPIView.as_view(),
        name="api-general-settings",
    ),
    path(
        "pagination-settings/",
        views.PaginationSettingsAPIView.as_view(),
        name="api-pagination-settings",
    ),
    path(
        "account-restrictions/",
        views.AccountRestrictionsAPIView.as_view(),
        name="api-account-restrictions",
    ),
    path(
        "badge-prefix/",
        views.BadgePrefixAPIView.as_view(),
        name="api-badge-prefix",
    ),
    path(
        "encashment-settings/",
        views.EncashmentSettingsAPIView.as_view(),
        name="api-encashment-settings",
    ),
    path(
        "currency-settings/",
        views.CurrencySettingsAPIView.as_view(),
        name="api-currency-settings",
    ),
    path(
        "resignation-request/",
        views.ResignationRequestAPIView.as_view(),
        name="api-resignation-request",
    ),
    path(
        "time-runner/",
        views.TimeRunnerAPIView.as_view(),
        name="api-time-runner",
    ),
    path(
        "notice-period/",
        views.NoticePeriodAPIView.as_view(),
        name="api-notice-period",
    ),
    path(
        "date-time-settings/",
        views.DateTimeSettingsAPIView.as_view(),
        name="api-date-time-settings",
    ),
    path(
        "audit-tags/",
        views.AuditTagListCreateView.as_view(),
        name="api-audit-tags-list",
    ),
    path(
        "audit-tags/<int:pk>/",
        views.AuditTagDetailView.as_view(),
        name="api-audit-tags-detail",
    ),
    path(
        "employee-permissions-meta/",
        views.EmployeePermissionsMetaAPIView.as_view(),
        name="api-employee-permissions-meta",
    ),
    path(
        "employee-permissions-get/",
        views.EmployeePermissionsGetAPIView.as_view(),
        name="api-employee-permissions-get",
    ),
    path(
        "employee-permissions-assign/",
        views.EmployeePermissionsAssignAPIView.as_view(),
        name="api-employee-permissions-assign",
    ),
    path(
        "employee-widget-filter/",
        views.EmployeeWidgetFilterAPIView.as_view(),
        name="api-employee-widget-filter",
    ),
    path(
        "employee-permissions-list/",
        views.EmployeePermissionsListAPIView.as_view(),
        name="api-employee-permissions-list",
    ),
    path(
        "accessibility/",
        views.AccessibilitySettingsAPIView.as_view(),
        name="api-accessibility-settings",
    ),
    path(
        "accessibility-settings/",
        views.AccessibilitySettingsAPIView.as_view(),
        name="api-accessibility-settings-alt",
    ),
    path(
        "user-groups/",
        views.UserGroupListCreateView.as_view(),
        name="api-user-groups-list",
    ),
    path(
        "user-groups/<int:pk>/",
        views.UserGroupDetailView.as_view(),
        name="api-user-groups-detail",
    ),
    path(
        "user-groups-assign/",
        views.UserGroupAssignView.as_view(),
        name="api-user-groups-assign",
    ),
    path(
        "mail-servers/",
        views.MailServerListCreateView.as_view(),
        name="api-mail-servers-list",
    ),
    path(
        "mail-servers/<int:pk>/",
        views.MailServerDetailView.as_view(),
        name="api-mail-servers-detail",
    ),
    path(
        "mail-servers-test-email/",
        views.MailServerTestEmailView.as_view(),
        name="api-mail-servers-test-email",
    ),
    path(
        "mail-servers-replace-primary/",
        views.MailServerReplacePrimaryView.as_view(),
        name="api-mail-servers-replace-primary",
    ),
    path(
        "gdrive-backup/",
        views.GdriveBackupAPIView.as_view(),
        name="api-gdrive-backup",
    ),
    path(
        "gdrive-backup-start-stop/",
        views.GdriveBackupStartStopView.as_view(),
        name="api-gdrive-backup-start-stop",
    ),
    path(
        "gdrive-backup-delete/",
        views.GdriveBackupDeleteView.as_view(),
        name="api-gdrive-backup-delete",
    ),
]
